#!/bin/bash
source ~/.zshrc
RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}Mpd installing and configuring${NC}..."
sleep 10
a=mpd
build=~/.config
build2=~/.local/share
sourcegit=https://raw.githubusercontent.com/c4tzz/dotfiles/master
mkdir -pv ~/{Music,Playlists,Lyrics}
mkdir -pv $build/$a
mkdir -pv $build2/$a && cd "$_"
touch $a.{db,log,pid,state} && touch sticker.sql && cd..
pacman -S --noconfirm $a
wget $sourcegit/mpd.conf
mv mpd.conf $build/$a





